# Generated by Django 4.2.2 on 2023-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_difficultylevel_topic_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(default='images/default.png', upload_to='course_photos/'),
        ),
    ]
