# Generated by Django 4.2.2 on 2023-08-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_category_alter_course_course_photo_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.ImageField(default='static/images/default.png', upload_to='category_images/'),
        ),
    ]
