# Generated by Django 4.2.4 on 2023-08-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
    ]
