# Generated by Django 4.2.4 on 2023-08-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
